### ISSUE TITLE
[BUG] Downloading mp4 no matter what I tell Seal to download?

### ISSUE THREAD

**Issue by TheSimpEternal** [JunkFood02/Seal#104]
(First github post, sorry if it's formatted weird or something)

So, it seems like no matter what I tell Seal to download, it downloads mp4 files and translates them once they're downloaded. I've got two experiences.

Last night, I told it to download an in-progress youtube stream as audio, specified as m4a. The final file is 153 MB. But when downloading, it was downloading an mp4 file. I don't know what resolution because I didn't get an option, but the mp4 ended up being about 4.1 GB . Once the stream ended, I tried playing the mp4, and it worked. When I left the player and went back to the file manager, the mp4 was inexplicably cloned, one of them was cut to m4a, and the other was deleted. But what I was expecting to take up 150 MB took up, at one point, 8 GB . 

Right now, I'm downloading another in-progress youtube stream, this time specified as 480p webm. But it's still downloading an mp4. Once it's done, I'll go watch the file manager and see if it clones the file again before spitting out a webm file.

(UPDATE: I watched it for 15 minutes after the stream ended, and it never said it was done downloading, cloned the mp4, or converted it to webm. I'll check in the morning if it's said it's done downloading or if it's converted to webm. The file is 1.37 GB and the stream was about 3 hours long, so I'm guessing it is 480p since the last 3 hour stream was 4.1 GB)

Idk if this is a bug or if this is just how it's supposed to work? This isn't how youtube-dl works on my pc, and if this is intended behavior, maybe it should be in the app description on F-Droid?

Oh, and in case it's relevant. I'm running version 1.0.0 , and am on an Andorid version 12 phone.

(Bug report's over, but I just wanted to say that this is a very nice app. It's more polished than I expected, and really easy to use. Thanks for all your work!)

**Comment by JunkFood02** [comment]
Seal currently uses yt-dlp for downloading instead of youtube-dl. I haven't used Seal for downloading a stream so far, but it should have the same behavior as on the desktop.
There's something for sure is that, when you download a **stream**, the yt-dlp will download all the segments with an M3U8 table, and merge them into a single file. If "save as audio" is on, yt-dlp would extract audio from this file and then delete the original one. If the stream has been archived, youtube would re-encode the stream into a regular video, which will provide audio-only formats for downloading.
Also, the **preferred** video format is just for **priority in sorting**, yt-dlp always chooses the best available format to download.

**Comment by TheSimpEternal** [comment]
Oh, ok. That did shed some light on that for me, thank you. I had no idea thats how it worked.

I guess this isn't a bug or really even an issue, then. Should I delete the post?
