### ISSUE TITLE
Crunchyroll Hardsub

### ISSUE THREAD

**Issue by meinarus** [JunkFood02/Seal#1211]

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/assets/41828058/e77609c3-ea07-4953-8ee0-7a8d41cb2c8a

**Comment by JunkFood02** [comment]
This feature request looks a bit complicated. Anyway @Marco-9456 provides some contexts here

> you'll need to do some match-filtering again and change the custom command every time you want to change them instead of just clicking them like on the GUI.

For what? Selecting episodes to download from a season, or selecting the format (in particular, hardsub video) to download from an episode?

**Comment by jeyemrs** [comment]
> For what? Selecting episodes to download from a season, or selecting the format (in particular, hardsub video) to download from an episode?

Both. Like if I used a series link from Crunchyroll, I can use the playlist option and there'll be a GUI where I can choose whatever episodes I want. While I can see the Japanese and English Dub there, there's no way to download them with hardsubs.

Basically an option to download hardsubs for both single episode link and series link (using playlist option)

**Comment by JunkFood02** [comment]
> there's no way to download them with hardsubs

Actually, yes. We don't know which formats a video has before we extract the information of it from the website. And if we do so to the whole playlist, the process will be unbearably slow. Even if the complete information of a episode gets extracted, we can not distingiush the hardsub videos from ones which are not

> using playlist option, where I can also choose what hardsubs episodes I want to download

The only solution at the moment might be to add additional custom commands for downloading in GUI mode, which seems like a overkill for this feature request. 

Since `--extractor-args crunchyrollbeta:hardsub=en-US --match-filter "language=ja-JP"` works for your use case, did you try using `--playlist-items` to select the episode you want to download from a series?
