### ISSUE TITLE
Add support for non-English title video file name

### ISSUE THREAD

**Issue by CanglanXYA** [JunkFood02/Seal#1269]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

If you download a non-English video like a Japan video with no alternative English title, the final video's file name will ignore the Japanese characters, which cause the video's file name seemed wired and incomplete.

**Comment by Marco-9456** [comment]
The downloaded file title is limited 
to `200 bytes` to avoid `Errno 36`, this Error happens when a file has a title that's more than `200B` in size so to avoid it we set a limit,  
none English characters like Japanese characters take more space than English characters (hiragana/katakana) take `3 bytes` and Kanji takes `4 bytes` that's the reason why the title seems messed up sometimes.

**Comment by JunkFood02** [comment]
Turn off restrict filename
