### ISSUE TITLE
Cant download hidden videos at Youtube

### ISSUE THREAD

**Issue by CanglanXYA** [JunkFood02/Seal#1270]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

If you try to download a video which was hidden by the youtuber, seal (or yt-dl) can download video info but quit at “downloading m3u8” step suddenly and show “download successfully” (in fact no such file at storage)

### Error reports

No such things, because the program thinks “Ive run successfully”.

**Comment by Marco-9456** [comment]
1. If the video is still hidden, Seal can't magically download it for you, this is impossible
2. The issue you're talking about is not related to the video availability, you have probably enabled the download archive option in the settings, this option when enabled makes the video record all the downloads you have done so that if you try to download the same video in the feature it won't let you if you don't want this behavior, simply go to the `Settings` --> `General` --> Toggle `Download archive` off.

**Comment by Marco-9456** [comment]
> That kind of hiding is just a sort of "shadow hiding", which means you can watch that video by typing or clicking the URL on YouTube but you can't search or fetch that video from the YouTuber's profile page.

Are you talking about videos that are not listed? If so then this should work.
Anyway, share a link to the video you're talking about.

**Comment by Marco-9456** [comment]
> https://youtu.be/1tOebwWox2E https://invidious.lunar.icu/watch?v=1tOebwWox2E (Same video)

The video downloaded normally
