### ISSUE TITLE
Multiple downloads at a time

### ISSUE THREAD

**Issue by Blanket72** [JunkFood02/Seal#1513]
### Checklist

- [x] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [x] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

The app is grat, one of the best ive ever used, but i cant figure out why this app doesnt support multiple video downloading at a time, like it wont let another video download when something else is already downloading at that time

**Comment by itskhero** [comment]
i agree to you because you can do multiple downloads by having the video be downloaded using the Quick Download but if it is the opening the Seal App way, it doesn't work and will just say (An existing download task is running)
is it because of the preview download, process stuffs or something else?

Quick download way

https://github.com/JunkFood02/Seal/assets/116128416/88241f6d-2bef-4812-91d2-da89fbb8f25b


Open Seal app way

https://github.com/JunkFood02/Seal/assets/116128416/fc1cc88e-237d-4baa-8a77-b91595d15562

**Comment by abdalrhmanyasser** [comment]
This would amazing and so useful please implement this i beg😅
