### ISSUE TITLE
Cant download YouTube videos 

### ISSUE THREAD

**Issue by Taha-dl** [JunkFood02/Seal#1599]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I can't download anything from YouTube.

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.25.232820

URL: https://youtube.com/watch?v=kBhmrb1i_VU&si=bJ869GDayo48x_ZY
ERROR: [youtube] kBhmrb1i_VU: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Screenshots & Screen Records

![Uploading SmartSelect_20240728_102251_Seal.jpg…]()

**Comment by vijjacarana** [comment]
App version: 1.12.1 (11212)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

URL: https://youtube.com/watch?v=ypbmjAF9m5w&si=ipK-vvSsSjrQIaA1
[debug] Command-line config: ['--no-mtime', '-v', '--download-archive', '/data/user/0/com.junkfood.seal/files/archive.txt', '--no-playlist', '--concurrent-fragments', '8', '--add-metadata', '--no-embed-info-json', '-S', 'proto,vcodec:h264,ext,res:720', '--write-auto-subs', '--extractor-args', 'youtube:skip=translated_subs', '--sub-langs', 'en.*,.*-orig', '--embed-subs', '--remux-video', 'mkv', '--merge-output-format', 'mkv', '--embed-chapters', '-P', '/storage/emulated/0/外语学习/Chat The Chat English Channel/电影英语 老友记', '-P', 'temp:/storage/emulated/0/Download/Seal/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.junkfood.seal-_lq04o-fafup61SM1rsYyw==/lib/arm64/libffmpeg.so', 'https://youtube.com/watch?v=ypbmjAF9m5w&si=ipK-vvSsSjrQIaA1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2023.02.17 [a0a7c01] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.14.116-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Loading archive file '/data/user/0/com.junkfood.seal/files/archive.txt'
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] ypbmjAF9m5w: nsig extraction failed: You may experience throttling for some formats
         n = husXHWhSc0Q1OssT ; player = https://www.youtube.com/s/player/0e90208b/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] ypbmjAF9m5w: nsig extraction failed: You may experience throttling for some formats
         n = 8Lzr5QBc6Q12rL_U ; player = https://www.youtube.com/s/player/0e90208b/player_ias.vflset/en_US/base.js
[debug] Sort order given by user: proto, vcodec:h264, ext, res:720
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, proto, vcodec:h264(7), vext, aext, res:720(720.0), quality, fps, hdr:12(7), source, channels, acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://rr2---sn-vvgxqvvht5oh5g-hqal.googlevideo.com/videoplayback?expire=1722291434&ei=isCnZpKyFcHp4t4PjdytQQ&ip=69.160.30.228&id=o-AMoBRN5KH5DL5J3ZH4pWrevMovPMjsOTF9NZgBjpCItp&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Hc&mm=31%2C29&mn=sn-vvgxqvvht5oh5g-hqal%2Csn-npoldn76&ms=au%2Crdu&mv=m&mvi=2&pl=24&pcm2=no&initcwndbps=281250&bui=AXc671KoH6WQBzy2K6UXmUZk2UCMjypimXsiJGkXL2awyt-x1eLTp1JMaQp9A_xI2XhVkuczj5DzyrPC&spc=NO7bAVCtOlI1edz8mIYkSnM_4ov1Knp42XO10eLhsBVFI108iZPYynE9is7T&vprv=1&svpuc=1&mime=video%2Fmp4&ns=M1E26XYcWeIYIuCApEI5ePMQ&rqh=1&gir=yes&clen=12096952&dur=62.333&lmt=1722219512931108&mt=1722269356&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=5309224&n=8Lzr5QBc6Q12rL_U&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cpcm2%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgYufowceBdbZShOnVfKsZHZrBlvNsY1iAvnvsLP-e-voCIGe76WpouE8w2pgRoO1qhugLulRjnqqD8JXZ4D_EPOHk&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRgIhAO_ENFbCjkmgoJl0tg3v9PwmoRPFT2497dl9ZLmFhCJdAiEA0yZueyBzNmu_WAHw7q3SaOnhm091gT0gMznsWSukNTQ%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3213, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2954, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 376, in real_download
    establish_connection()
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3726, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
