### ISSUE TITLE
Suggestions + Fix

### ISSUE THREAD

**Issue by UserAccount123** [JunkFood02/Seal#1701]
# SUGGESTIONS:
1. Enable adding incremental numbering to playlist items.
2. Enable to add multiple links at one time (by pasting them in (Video link) box).
3. Add ability to pause/resume.
4. Enable to select number of files to be download simultaneously.
5. Enable opening YouTube inside the app (to download videos/playlist/channel).
6. Enable selecting multiple videos from YouTube channel to download.
7. Enable to export/import settings.

# FIXES:
- Downloaded files are not shown inside (Downloads) buttons.

**Comment by BobbyESP** [comment]
Hi. First of all thanks for opening the issue. I want to clarify some things:
- The specific options related to external apps (like YouTube) probably won't be added. Seal was created to be a yt-dlp GUI for Android, but not to have specific-app features, so that the app remains simple for ANY website supported by the library
- The second option that you mention I believe that it is already implemented by separing them in new lines (I'm not sure of this one). You can check it by yourself.
- The pause/resume ability probably also won't come since is something that yt-dlp does not support. Anyways, if you stop a video and retry to download it, the process will remain saved (cache files are saved in the app)

Hope that you understand. If you have any further questions, we are here
