### ISSUE TITLE
Error using --download-archive

### ISSUE THREAD

**Issue by johnredfield2099** [JunkFood02/Seal#201]
ERROR: [Errno 30] Read-only file system: 'archive.txt'
How fix this ?

**Comment by JunkFood02** [comment]
Still got no idea about how to handle this
- https://github.com/JunkFood02/Seal/issues/182#issuecomment-1236119559

**Comment by johnredfield2099** [comment]
Thanks for the answer.

**Comment by jo-chemla** [comment]
Hi there, when trying to use the `--download-archive archive.txt` option, I get the same error `ERROR: [Errno 30] Read-only file system: 'archive.txt'`. Could not find a way to prevent this on the referenced thread. I wanted to use the folder where Seal downloads videos/audios since I already allowed the app read-write access to it, maybe it is just a matter of specifying the `archive.txt` folderpath correctly?

**Comment by Marco-9456** [comment]
>Hi there, when trying to use the --download-archive archive.txt option, I get the same error ERROR: [Errno 30] Read-only file system: 'archive.txt'

Go to your phone settings and search for all file access, and give that permission to Seal.

**Comment by jo-chemla** [comment]
Thanks for getting back, as shown my fix was to use an absolute path for that archive file, that points to the location I already authorized Seal RW access to.

**Comment by JunkFood02** [comment]
Added in v1.11.0-beta.2
