### ISSUE TITLE
Monet doesn't work.

### ISSUE THREAD

**Issue by chathura7357** [JunkFood02/Seal#229]
I am using the app on my galaxy A72, which is currently on One UI 4.1 on top of Android 12. So as obvious material you theming in apps is here. But Seal doesnt change its colour pallete according to the wallpaper like other supported apps. (Ex - Taptap, Google apps with theming support, Neostore,Metro)  And I dug in to the settings but there I was only able to find some pre defined colour options other than a toggle for turn on or off Monet. If this is a issue #of the app, please fix it. If this some mistake or misunderstanding of the app UI by me, then please help me to work it out. Anyway  #thank you for creating such a useful app.

**Comment by BobbyESP** [comment]
Correct me if it's not true @JunkFood02 , but this app was desgined to have the Monet experience in all the devices that the app supports (i think API 21). So that's why in settings you have some palettes that you can choose to accord with your wallpaper. By the way, the app (by the moment) don't support Android 12> Monet system matching, so it's neccesary to choose the palette you want.

**Comment by JunkFood02** [comment]
The first color in the palette of the display settings reflects the wallpaper/color scheme you're using, automatically changing color is not implement due to compatibility

**Comment by JunkFood02** [comment]
Added in v1.3.4
