### ISSUE TITLE
[Feature Request] More video format conversions

### ISSUE THREAD

**Issue by chiyi4488** [JunkFood02/Seal#249]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

N. 

### Describe the solution you'd like

I recommended to add more file conversion format options.

yt-dlp supports many different video formats. If can directly select it in the "Configure before downloading" screen, I think it will be more user-friendly, so that users don't need to customize commands.

建議新增更多的檔案轉檔格式選項。

 yt-dlp 支援許多不同的影片格式，若能直接在「下載前配置」畫面中選取，我想這會對用戶更加友善，讓用戶不需要自訂指令。

**Comment by JunkFood02** [comment]
This may be a bit complicated. In short, the general mode in Seal does not and will not contain any "conversion" for video formats. The "preferred video format" is only about format selecting or sorting. This is because we believe that the original format from the website already meets our expectations with the quality and the file size, any conversion made to the video would bring a loss of quality and longer processing time.

**Comment by chiyi4488** [comment]
I got it. Is it possible to add it to the "convert" option? Make the convert option not limited to converting to audio files.

我明白了，有沒有可能將其新增在「轉換」選項中呢？讓轉換功能不再侷限在轉換成音檔。

**Comment by JunkFood02** [comment]
> Make the convert option not limited to converting to audio files.

That's what I mean because I want the general mode to be as simple as possible. In most cases, converting videos into other formats is not necessary. If needed, use a custom command instead.
