### ISSUE TITLE
counter [Feature Request]

### ISSUE THREAD

**Issue by xyen8180** [JunkFood02/Seal#394]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

youtube videos can be arranged customly, so whenever i download a playlist from youtube videos get downloaded but in phone's memory it sorted by alphabetically so the orders get messed up

### Describe the solution you'd like

 i want whenever playlist gets downloaded i want a number should be set on prefix like video 1 this.mp4, 2 this.mp4 and so on.

**Comment by JunkFood02** [comment]
Download directory - Custom subdirectory - set the template to `%(playlist_index)d - `, you'll get file names like "3 - title.mp4"

**Comment by xyen8180** [comment]
thank you so much brother 🥰

**Comment by NajliDePujli** [comment]
App version: 1.8.0-rc.1 (10800)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://fb.watch/i634amEsf0/
ERROR: [generic] None: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Fix this issues
