### ISSUE TITLE
[Bug Report] Fast download is not working properly.

### ISSUE THREAD

**Issue by Ilhamiii** [JunkFood02/Seal#514]
### Describe the bug

Fast download is not working properly.

### To Reproduce

1.Play the video.
2.Click on quick download to download the video.
3.The video download configuration page opens, but the format selection page does not open.
4.Video not downloaded.

### Error reports & Screenshots

https://user-images.githubusercontent.com/121803062/212863735-0ba5b307-9ae0-4348-858e-527dc99ee7e6.mp4

### Device info

App version: 1.8.0-rc.1 (10800)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

The download should start immediately and continue in the application.The main problem is in the choice of format.

**Comment by Marco-9456** [comment]
> 

Which one do you mean:

<details markdown='1'><summary>1. This:</summary>

https://user-images.githubusercontent.com/41828058/212900207-aaafed40-bb51-41b4-b5f7-a79369b81b98.mp4

</details>

<details markdown='1'><summary>2. This:</summary>

https://user-images.githubusercontent.com/41828058/212900280-a108c529-24c5-4d32-9030-c0f34668c3a7.mp4

</details>


- If you mean the first one then this isn't meant to be available in `Quick download` because it's supposed to be QUICK

- If the second one then please wait tell we figure out where the problem is.
