### ISSUE TITLE
[Feature Request] Alternative means of distribution other than F-Droid?

### ISSUE THREAD

**Issue by Pentaphon** [JunkFood02/Seal#683]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

F-Droid is taking forever to update the app on their side and their build process is slow. Is there any chance of having another way to get updates for this app? Like a self-updater for the Github version? 

### Describe the solution you'd like

A self-updater for the Github release would be great. 

### Video link

N/A

**Comment by Marco-9456** [comment]
> ### Is your feature request related to a problem? Please describe.
> F-Droid is taking forever to update the app on their side and their build process is slow. Is there any chance of having another way to get updates for this app? Like a self-updater for the GitHub version?

There is no need for a "Self-Updater" the app already have Auto update functionality but the thing is that F-Droid version of the app is not able to preform it because auto update source is GitHub builds and you can't update an F-Droid Version of the app with an GitHub one because they have different signatures.

The solution for you will be to download latest [GitHub Build](https://github.com/JunkFood02/Seal/releases/tag/v1.9.0)  of the app and turn auto update from the app settings on, this way you will get the newest directly after its published here.
