### ISSUE TITLE
[Feature Request] merge audio directly to video container if possible

### ISSUE THREAD

**Issue by soredake** [JunkFood02/Seal#684]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Right now after downloading split formats from youtube (e.g. .webm/.mp4 + .opus/.m4a) they are merged into dedicated new .mkv which requires a lot more space.

### Describe the solution you'd like

It would be nice if new option can be added, "Merge audio directly to video container" which will limit your audio format choices (e.g. if you choose `webm` video format you can only choose `opus` audio as webm container does not support aac), and after downloading audio and video files audio will be merged directly into video container (e.g. .opus -> .webm), merging audio directly into downloaded video container will require less (or much less depending on video size) space.

### Additional context

I first encountered space problem with this video (~12gb) https://www.youtube.com/watch?v=rzggQZ2IXKo, i had ~15gb free, tried downloading and got "Conversion error", then i realized i need 24gb as files merged to dedicated mkv after downloading.

**Comment by JunkFood02** [comment]
Merging is automatically done by FFmpeg & yt-dlp and we cannot do anything about it. Maybe you want to take a look at the part of format selection in the yt-dlp manual. For instance, `-f 141,251` will download two formats separately.

The built-in FFmpeg in Seal is outdated, hard to update and basically a minimal subset for running basic yt-dlp task on Android mobile devices. If you really want to execute such a heavy task on your device, I'll suggest to switch to Termux or other Linux distros instead of running Seal in Android environment.

**Comment by soredake** [comment]
Reported to yt-dlp https://github.com/yt-dlp/yt-dlp/issues/7250
