### ISSUE TITLE
Improve mp3 file art quality and its download quality to 320 kbps

### ISSUE THREAD

**Issue by CR4ZYDANI** [JunkFood02/Seal#953]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I would like these options to be added or if they can be configured, post what the process is like
![Screenshot_2023-07-22-20-46-32-329_com miui player](https://github.com/JunkFood02/Seal/assets/73937080/17ffa239-ddfd-4004-9315-3558e00c777c)

**Comment by JunkFood02** [comment]
When you download audio from YouTube or other platforms, you can only access the formats provided by the platform. YouTube usually offers 128 kbps OPUS/M4A formats, or 256 kbps for YouTube Premium and YT Music users.

Some apps might promise to convert the audio to higher quality formats like 320 kbps MP3, but it's important to understand that this won't actually enhance the audio quality. In fact, it may even reduce the quality and increase the file size, since the audio will be re-encoded and compressed again. So, unless you have a specific reason to convert it, it's generally best to use the original audio format provided by the platform.

**Comment by CR4ZYDANI** [comment]
> Cuando descarga audio de YouTube u otras plataformas, solo puede acceder a los formatos proporcionados por la plataforma. YouTube suele ofrecer formatos OPUS/M4A de 128 kbps o 256 kbps para usuarios de YouTube Premium y YT Music.
> 
> Algunas aplicaciones pueden prometer convertir el audio a formatos de mayor calidad, como MP3 de 320 kbps, pero es importante comprender que esto en realidad no mejorará la calidad del audio. De hecho, puede incluso reducir la calidad y aumentar el tamaño del archivo, ya que el audio se recodificará y comprimirá nuevamente. Entonces, a menos que tenga una razón específica para convertirlo, generalmente es mejor usar el formato de audio original provisto por la plataforma.

and the quality of the cover can be changed?
